/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductSectionDesign = {
  _id: string;
  _type: "productSectionDesign";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  breakpoint?: "md" | "lg";
  flipLayout?: boolean;
  columnRatio?: RangeSlider;
  gap?: {
    desktop?: RangeSlider;
    mobile?: RangeSlider;
  };
  detailsPadding?: {
    desktop?: {
      x?: RangeSlider;
      y?: RangeSlider;
    };
    mobile?: {
      x?: RangeSlider;
      y?: RangeSlider;
    };
  };
  mobileLayout?: "mediaFirst" | "headerFirst";
  mobileHeaderContent?: {
    showVendor?: boolean;
    showTitle?: boolean;
    showReviews?: boolean;
    showPrice?: boolean;
  };
  mobileHeaderPaddingY?: RangeSlider;
  galleryDisplay?: "carousel" | "vertical" | "grid";
  gridGap?: RangeSlider;
  mediaBorderRadius?: RangeSlider;
  showArrows?: boolean;
  showThumbnails?: boolean;
  thumbnailOptions?: {
    position?: "left" | "bottom";
    overlayOnImage?: boolean;
    borderRadius?: RangeSlider;
  };
  mediaInteraction?: "lightbox" | "zoom" | "none";
  showThumbnailsOnMobile?: boolean;
  showDots?: boolean;
};

export type RangeSlider = number;

export type ThemeContent = {
  _id: string;
  _type: "themeContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  account?: {
    welcome?: InternationalizedArrayString;
    welcomeToYourAccount?: InternationalizedArrayString;
    accountDetails?: InternationalizedArrayString;
    signOut?: InternationalizedArrayString;
    orderHistory?: InternationalizedArrayString;
    noOrdersMessage?: InternationalizedArrayString;
    startShopping?: InternationalizedArrayString;
    orderDetail?: InternationalizedArrayString;
    returnToAccount?: InternationalizedArrayString;
    orderNumber?: InternationalizedArrayString;
    placedOn?: InternationalizedArrayString;
    product?: InternationalizedArrayString;
    price?: InternationalizedArrayString;
    quantity?: InternationalizedArrayString;
    total?: InternationalizedArrayString;
    subtotal?: InternationalizedArrayString;
    discounts?: InternationalizedArrayString;
    discountsOff?: InternationalizedArrayString;
    tax?: InternationalizedArrayString;
    shippingAddress?: InternationalizedArrayString;
    noShippingAddress?: InternationalizedArrayString;
    status?: InternationalizedArrayString;
    updateYourProfile?: InternationalizedArrayString;
    firstName?: InternationalizedArrayString;
    lastName?: InternationalizedArrayString;
    company?: InternationalizedArrayString;
    addressLine1?: InternationalizedArrayString;
    addressLine2?: InternationalizedArrayString;
    city?: InternationalizedArrayString;
    stateProvince?: InternationalizedArrayString;
    postalCode?: InternationalizedArrayString;
    country?: InternationalizedArrayString;
    phone?: InternationalizedArrayString;
    defaultAddress?: InternationalizedArrayString;
    saving?: InternationalizedArrayString;
    save?: InternationalizedArrayString;
    cancel?: InternationalizedArrayString;
    addName?: InternationalizedArrayString;
    addAddress?: InternationalizedArrayString;
    editAddress?: InternationalizedArrayString;
    addressBook?: InternationalizedArrayString;
    noAddress?: InternationalizedArrayString;
    default?: InternationalizedArrayString;
    edit?: InternationalizedArrayString;
    remove?: InternationalizedArrayString;
    profile?: InternationalizedArrayString;
    name?: InternationalizedArrayString;
    phoneNumber?: InternationalizedArrayString;
    emailAddress?: InternationalizedArrayString;
    orderId?: InternationalizedArrayString;
    orderDate?: InternationalizedArrayString;
    fulfillmentStatus?: InternationalizedArrayString;
    viewDetails?: InternationalizedArrayString;
    orderStatusCancelled?: InternationalizedArrayString;
    orderStatusError?: InternationalizedArrayString;
    orderStatusFailure?: InternationalizedArrayString;
    orderStatusOpen?: InternationalizedArrayString;
    orderStatusPending?: InternationalizedArrayString;
    orderStatusSuccess?: InternationalizedArrayString;
  };
  cart?: {
    heading?: InternationalizedArrayString;
    proceedToCheckout?: InternationalizedArrayString;
    orderSummary?: InternationalizedArrayString;
    subtotal?: InternationalizedArrayString;
    discounts?: InternationalizedArrayString;
    applyDiscount?: InternationalizedArrayString;
    discountCode?: InternationalizedArrayString;
    remove?: InternationalizedArrayString;
    quantity?: InternationalizedArrayString;
    continueShopping?: InternationalizedArrayString;
    emptyMessage?: InternationalizedArrayString;
  };
  collection?: {
    sortBy?: InternationalizedArrayString;
    sortFeatured?: InternationalizedArrayString;
    sortLowHigh?: InternationalizedArrayString;
    sortHighLow?: InternationalizedArrayString;
    sortBestSelling?: InternationalizedArrayString;
    sortNewest?: InternationalizedArrayString;
    filterAndSort?: InternationalizedArrayString;
    from?: InternationalizedArrayString;
    to?: InternationalizedArrayString;
    filterInStock?: InternationalizedArrayString;
    filterOutOfStock?: InternationalizedArrayString;
    viewAll?: InternationalizedArrayString;
    clearFilters?: InternationalizedArrayString;
    clear?: InternationalizedArrayString;
    apply?: InternationalizedArrayString;
    loading?: InternationalizedArrayString;
    loadPrevious?: InternationalizedArrayString;
    loadMoreProducts?: InternationalizedArrayString;
    noProductFound?: InternationalizedArrayString;
    noCollectionFound?: InternationalizedArrayString;
  };
  product?: {
    addToCart?: InternationalizedArrayString;
    sale?: InternationalizedArrayString;
    soldOut?: InternationalizedArrayString;
    quantitySelector?: InternationalizedArrayString;
  };
  error?: {
    pageNotFound?: InternationalizedArrayString;
    serverError?: InternationalizedArrayString;
    sectionError?: InternationalizedArrayString;
    reloadPage?: InternationalizedArrayString;
    missingAddressId?: InternationalizedArrayString;
    addressCreation?: InternationalizedArrayString;
  };
};

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteDescription?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialSharingImagePreview?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  spaceBetweenTemplateSections?: RangeSlider;
  containerMaxWidth?: RangeSlider;
  buttonsBorder?: {
    thickness?: RangeSlider;
    opacity?: RangeSlider;
    cornerRadius?: RangeSlider;
  };
  buttonsShadow?: {
    opacity?: RangeSlider;
    horizontalOffset?: RangeSlider;
    verticalOffset?: RangeSlider;
    blur?: RangeSlider;
  };
  inputsBorder?: {
    thickness?: RangeSlider;
    opacity?: RangeSlider;
    cornerRadius?: RangeSlider;
  };
  inputsShadow?: {
    opacity?: RangeSlider;
    horizontalOffset?: RangeSlider;
    verticalOffset?: RangeSlider;
    blur?: RangeSlider;
  };
  productCards?: {
    style?: "standard" | "card";
    imageAspectRatio?: AspectRatios;
    textAlignment?: "left" | "center" | "right";
    border?: {
      thickness?: RangeSlider;
      opacity?: RangeSlider;
      cornerRadius?: RangeSlider;
    };
    shadow?: {
      opacity?: RangeSlider;
      horizontalOffset?: RangeSlider;
      verticalOffset?: RangeSlider;
      blur?: RangeSlider;
    };
  };
  collectionCards?: {
    style?: "standard" | "card";
    imageAspectRatio?: AspectRatios;
    textAlignment?: "left" | "center" | "right";
    border?: {
      thickness?: RangeSlider;
      opacity?: RangeSlider;
      cornerRadius?: RangeSlider;
    };
    shadow?: {
      opacity?: RangeSlider;
      horizontalOffset?: RangeSlider;
      verticalOffset?: RangeSlider;
      blur?: RangeSlider;
    };
  };
  blogCards?: {
    style?: "standard" | "card";
    imageAspectRatio?: AspectRatios;
    textAlignment?: "left" | "center" | "right";
    border?: {
      thickness?: RangeSlider;
      opacity?: RangeSlider;
      cornerRadius?: RangeSlider;
    };
    shadow?: {
      opacity?: RangeSlider;
      horizontalOffset?: RangeSlider;
      verticalOffset?: RangeSlider;
      blur?: RangeSlider;
    };
  };
  mediaBorder?: {
    thickness?: RangeSlider;
    opacity?: RangeSlider;
    cornerRadius?: RangeSlider;
  };
  mediaShadow?: {
    opacity?: RangeSlider;
    horizontalOffset?: RangeSlider;
    verticalOffset?: RangeSlider;
    blur?: RangeSlider;
  };
  dropdownsAndPopupsBorder?: {
    thickness?: RangeSlider;
    opacity?: RangeSlider;
    cornerRadius?: RangeSlider;
  };
  dropdownsAndPopupsShadow?: {
    opacity?: RangeSlider;
    horizontalOffset?: RangeSlider;
    verticalOffset?: RangeSlider;
    blur?: RangeSlider;
  };
  badgesPosition?: "bottom_left" | "bottom_right" | "top_left" | "top_right";
  badgesCornerRadius?: RangeSlider;
  badgesSaleColorScheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "colorScheme";
  };
  badgesSoldOutColorScheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "colorScheme";
  };
  cartCollection?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  };
  cartColorScheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "colorScheme";
  };
  grid?: {
    horizontalSpace?: RangeSlider;
    verticalSpace?: RangeSlider;
  };
  facebook?: string;
  instagram?: string;
  tiktok?: string;
  twitter?: string;
  youtube?: string;
  linkedin?: string;
  snapchat?: string;
  pinterest?: string;
  tumblr?: string;
  vimeo?: string;
};

export type AspectRatios = "square" | "video" | "auto";

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Sections;
  footers?: Footers;
};

export type Footers = Array<{
  _key: string;
} & SocialLinksOnly>;

export type Sections = Array<{
  _key: string;
} & ImageBannerSection | {
  _key: string;
} & FeaturedCollectionSection | {
  _key: string;
} & FeaturedProductSection | {
  _key: string;
} & CollectionListSection | {
  _key: string;
} & CarouselSection | {
  _key: string;
} & RichtextSection>;

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menu?: InternationalizedArrayHeaderNavigation;
  announcementBar?: InternationalizedArrayAnnouncementBar;
  utilityLinks?: InternationalizedArrayLink;
  announcementBarColorScheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "colorScheme";
  };
  autoRotateAnnouncements?: boolean;
  showAnnouncementArrows?: boolean;
  announcementBarTextSize?: RangeSlider;
  announcementBarPadding?: Padding;
  desktopLayout?: "classic" | "centerLogo" | "threeColumn" | "splitRight";
  mobileLayout?: "balanced" | "menuLeft" | "brandLeft";
  desktopLogoWidth?: RangeSlider;
  showLocalizationSelector?: boolean;
  showWishlist?: boolean;
  accountStyleDesktop?: "icon" | "text";
  cartStyleDesktop?: "icon" | "text";
  cartStyleMobile?: "icon" | "text";
  colorScheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "colorScheme";
  };
  blur?: boolean;
  showSeparatorLine?: boolean;
  padding?: Padding;
  sticky?: "none" | "onScrollUp" | "always";
};

export type Padding = {
  _type: "padding";
  top?: RangeSlider;
  bottom?: RangeSlider;
};

export type InternationalizedArrayLink = Array<{
  _key: string;
} & InternationalizedArrayLinkValue>;

export type InternationalizedArrayAnnouncementBar = Array<{
  _key: string;
} & InternationalizedArrayAnnouncementBarValue>;

export type InternationalizedArrayHeaderNavigation = Array<{
  _key: string;
} & InternationalizedArrayHeaderNavigationValue>;

export type SocialLinksOnly = {
  _type: "socialLinksOnly";
  copyright?: InternationalizedArrayString;
  settings?: SectionSettings;
};

export type RichtextSection = {
  _type: "richtextSection";
  richtext?: InternationalizedArrayRichtext;
  desktopContentPosition?: ContentAlignment;
  contentAlignment?: ContentAlignment;
  maxWidth?: RangeSlider;
  settings?: SectionSettings;
};

export type RelatedProductsSection = {
  _type: "relatedProductsSection";
  heading?: InternationalizedArrayString;
  maxProducts?: RangeSlider;
  desktopColumns?: RangeSlider;
  settings?: SectionSettings;
};

export type ProductHeroSection = {
  _type: "productHeroSection";
  richtext?: InternationalizedArrayProductRichtext;
  mediaAspectRatio?: AspectRatios;
  settings?: SectionSettings;
};

export type ImageBannerSection = {
  _type: "imageBannerSection";
  content?: InternationalizedArrayBannerRichtext;
  contentPosition?: ContentPosition;
  contentAlignment?: ContentAlignment;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bannerHeight?: RangeSlider;
  overlayOpacity?: RangeSlider;
  settings?: SectionSettings;
};

export type FeaturedProductSection = {
  _type: "featuredProductSection";
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  richtext?: InternationalizedArrayProductRichtext;
  mediaAspectRatio?: AspectRatios;
  settings?: SectionSettings;
};

export type FeaturedCollectionSection = {
  _type: "featuredCollectionSection";
  heading?: InternationalizedArrayString;
  collection?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  };
  maxProducts?: RangeSlider;
  desktopColumns?: RangeSlider;
  viewAll?: boolean;
  settings?: SectionSettings;
};

export type CollectionProductGridSection = {
  _type: "collectionProductGridSection";
  productsPerPage?: RangeSlider;
  desktopColumns?: RangeSlider;
  mobileColumns?: RangeSlider;
  enableFiltering?: boolean;
  enableSorting?: boolean;
  settings?: SectionSettings;
};

export type CollectionListSection = {
  _type: "collectionListSection";
  collections?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "collection";
  }>;
  desktopColumns?: RangeSlider;
  settings?: SectionSettings;
};

export type CollectionBannerSection = {
  _type: "collectionBannerSection";
  showImage?: boolean;
  showDescription?: boolean;
  contentPosition?: ContentPosition;
  contentAlignment?: ContentAlignment;
  bannerHeight?: RangeSlider;
  overlayOpacity?: RangeSlider;
  settings?: SectionSettings;
};

export type CarouselSection = {
  _type: "carouselSection";
  title?: InternationalizedArrayString;
  pagination?: boolean;
  arrows?: boolean;
  autoplay?: boolean;
  loop?: boolean;
  slidesPerViewDesktop?: RangeSlider;
  slides?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "slide";
    _key: string;
  }>;
  settings?: SectionSettings;
};

export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hidden?: string;
  titleProxy?: ProxyString;
  store?: ShopifyProductVariant;
};

export type ShopifyProductVariant = {
  _type: "shopifyProductVariant";
  createdAt?: string;
  updatedAt?: string;
  status?: "active" | "archived" | "draft";
  isDeleted?: boolean;
  title?: string;
  sku?: string;
  id?: number;
  gid?: string;
  productId?: number;
  productGid?: string;
  price?: number;
  compareAtPrice?: number;
  inventory?: Inventory;
  option1?: string;
  option2?: string;
  option3?: string;
  previewImageUrl?: string;
};

export type ProxyString = string;

export type Typography = {
  _id: string;
  _type: "typography";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: {
    font?: Array<{
      _key: string;
    } & FontCategory>;
    capitalize?: boolean;
    baseSize?: RangeSlider;
    letterSpacing?: RangeSlider;
    lineHeight?: RangeSlider;
  };
  body?: {
    font?: Array<{
      _key: string;
    } & FontCategory>;
    baseSize?: RangeSlider;
    letterSpacing?: RangeSlider;
    lineHeight?: RangeSlider;
  };
  extra?: {
    font?: Array<{
      _key: string;
    } & FontCategory>;
    capitalize?: boolean;
    baseSize?: RangeSlider;
    letterSpacing?: RangeSlider;
    lineHeight?: RangeSlider;
  };
};

export type CollectionRule = {
  _type: "collectionRule";
  column?: string;
  relation?: string;
  condition?: string;
};

export type ShopifyCollection = {
  _type: "shopifyCollection";
  createdAt?: string;
  updatedAt?: string;
  isDeleted?: boolean;
  title?: string;
  id?: number;
  gid?: string;
  slug?: Slug;
  descriptionHtml?: string;
  imageUrl?: string;
  rules?: Array<{
    _key: string;
  } & CollectionRule>;
  disjunctive?: boolean;
  sortOrder?: string;
};

export type Inventory = {
  _type: "inventory";
  isAvailable?: boolean;
  management?: string;
  policy?: string;
};

export type ShopifyProduct = {
  _type: "shopifyProduct";
  createdAt?: string;
  updatedAt?: string;
  status?: "active" | "archived" | "draft";
  isDeleted?: boolean;
  title?: string;
  id?: number;
  gid?: string;
  slug?: Slug;
  descriptionHtml?: string;
  productType?: string;
  vendor?: string;
  tags?: string;
  priceRange?: PriceRange;
  previewImageUrl?: string;
  options?: Array<{
    _key: string;
  } & Option>;
  variants?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "productVariant";
  }>;
};

export type PriceRange = {
  _type: "priceRange";
  minVariantPrice?: number;
  maxVariantPrice?: number;
};

export type PlaceholderString = string;

export type Option = {
  _type: "option";
  name?: string;
  values?: Array<string>;
};

export type FontCategory = {
  _type: "fontCategory";
  fontName?: string;
  fontType?: "serif" | "sans-serif";
  antialiased?: boolean;
  fontAssets?: Array<{
    _key: string;
  } & FontAsset>;
};

export type FontAsset = {
  _type: "fontAsset";
  woff2?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  woff?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  ttf?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  fontStyle?: "normal" | "italic";
  fontWeight?: 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
};

export type MegaMenu = {
  _type: "megaMenu";
  name?: string;
  link?: Link;
  content?: Array<{
    heading?: string;
    headingLink?: Link;
    links?: Array<{
      _key: string;
    } & InternalLink | {
      _key: string;
    } & ExternalLink>;
    _type: "linkSection";
    _key: string;
  } | {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    heading?: string;
    description?: string;
    link?: Link;
    linkText?: string;
    _type: "imageBlock";
    _key: string;
  }>;
};

export type NestedNavigation = {
  _type: "nestedNavigation";
  name?: string;
  link?: Link;
  childLinks?: Array<{
    _key: string;
  } & InternalLink | {
    _key: string;
  } & ExternalLink>;
};

export type Link = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
} | {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
} | {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
} | {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "collection";
} | {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type InternalLink = {
  _type: "internalLink";
  name?: string;
  link?: Link;
  anchor?: Anchor;
};

export type Button = {
  _type: "button";
  label?: string;
  link?: Link;
  anchor?: Anchor;
};

export type HeaderNavigation = Array<{
  _key: string;
} & InternalLink | {
  _key: string;
} & ExternalLink | {
  _key: string;
} & NestedNavigation | {
  _key: string;
} & MegaMenu>;

export type ExternalLink = {
  _type: "externalLink";
  name?: string;
  link?: string;
  openInNewTab?: boolean;
};

export type Anchor = string;

export type Seo = {
  _type: "seo";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProductSections = Array<{
  _key: string;
} & ProductHeroSection | {
  _key: string;
} & RelatedProductsSection | {
  _key: string;
} & ImageBannerSection | {
  _key: string;
} & FeaturedCollectionSection | {
  _key: string;
} & FeaturedProductSection | {
  _key: string;
} & CollectionListSection | {
  _key: string;
} & CarouselSection | {
  _key: string;
} & RichtextSection>;

export type CollectionSections = Array<{
  _key: string;
} & CollectionBannerSection | {
  _key: string;
} & CollectionProductGridSection | {
  _key: string;
} & ImageBannerSection | {
  _key: string;
} & FeaturedCollectionSection | {
  _key: string;
} & FeaturedProductSection | {
  _key: string;
} & CollectionListSection | {
  _key: string;
} & CarouselSection | {
  _key: string;
} & RichtextSection>;

export type SectionSettings = {
  _type: "sectionSettings";
  hide?: boolean;
  colorScheme?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "colorScheme";
  };
  padding?: Padding;
  customCss?: Code;
};

export type ColorScheme = {
  _id: string;
  _type: "colorScheme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  default?: boolean;
  background?: ColorPicker;
  foreground?: ColorPicker;
  primary?: ColorPicker;
  primaryForeground?: ColorPicker;
  border?: ColorPicker;
  card?: ColorPicker;
  cardForeground?: ColorPicker;
};

export type ColorPicker = {
  _type: "colorPicker";
  hex?: string;
  hsl?: {
    h?: number;
    s?: number;
    l?: number;
  };
  rgb?: {
    r?: number;
    g?: number;
    b?: number;
  };
};

export type Richtext = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    link?: Link;
    anchor?: Anchor;
    _type: "internalLink";
    _key: string;
  } | {
    link?: string;
    openInNewTab?: boolean;
    _type: "externalLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  maxWidth?: RangeSlider;
  alignment?: ContentAlignment;
  _type: "image";
  _key: string;
} | {
  _key: string;
} & Button>;

export type ProductRichtext = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    link?: Link;
    anchor?: Anchor;
    _type: "internalLink";
    _key: string;
  } | {
    link?: string;
    openInNewTab?: boolean;
    _type: "externalLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  titleProxy?: ProxyString;
  _type: "shopifyTitle";
  _key: string;
} | {
  descriptionProxy?: ProxyString;
  _type: "shopifyDescription";
  _key: string;
} | {
  priceProxy?: ProxyString;
  _type: "price";
  _key: string;
} | {
  quantitySelector?: boolean;
  shopPayButton?: boolean;
  _type: "addToCartButton";
  _key: string;
}>;

export type ContentPosition = "top_left" | "top_center" | "top_right" | "middle_left" | "middle_center" | "middle_right" | "bottom_left" | "bottom_center" | "bottom_right";

export type ContentAlignment = "left" | "center" | "right";

export type BannerRichtext = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & Button>;

export type AnnouncementBar = Array<{
  text?: string;
  link?: Link;
  externalLink?: string;
  openInNewTab?: boolean;
  _type: "announcement";
  _key: string;
}>;

export type InternationalizedArrayLinkValue = {
  _type: "internationalizedArrayLinkValue";
  value?: Link;
};

export type InternationalizedArrayBannerRichtextValue = {
  _type: "internationalizedArrayBannerRichtextValue";
  value?: BannerRichtext;
};

export type InternationalizedArrayRichtextValue = {
  _type: "internationalizedArrayRichtextValue";
  value?: Richtext;
};

export type InternationalizedArrayProductRichtextValue = {
  _type: "internationalizedArrayProductRichtextValue";
  value?: ProductRichtext;
};

export type InternationalizedArrayAnnouncementBarValue = {
  _type: "internationalizedArrayAnnouncementBarValue";
  value?: AnnouncementBar;
};

export type InternationalizedArrayHeaderNavigationValue = {
  _type: "internationalizedArrayHeaderNavigationValue";
  value?: HeaderNavigation;
};

export type InternationalizedArraySlugValue = {
  _type: "internationalizedArraySlugValue";
  value?: Slug;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type InternationalizedArrayBannerRichtext = Array<{
  _key: string;
} & InternationalizedArrayBannerRichtextValue>;

export type InternationalizedArrayRichtext = Array<{
  _key: string;
} & InternationalizedArrayRichtextValue>;

export type InternationalizedArrayProductRichtext = Array<{
  _key: string;
} & InternationalizedArrayProductRichtextValue>;

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Sections;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  sections?: Sections;
  seo?: Seo;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hidden?: string;
  template?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productTemplate";
  };
  titleProxy?: ProxyString;
  slugProxy?: ProxyString;
  store?: ShopifyProduct;
};

export type ProductTemplate = {
  _id: string;
  _type: "productTemplate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  default?: boolean;
  sections?: ProductSections;
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hidden?: string;
  titleProxy?: ProxyString;
  slugProxy?: ProxyString;
  template?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collectionTemplate";
  };
  store?: ShopifyCollection;
};

export type CollectionTemplate = {
  _id: string;
  _type: "collectionTemplate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  default?: boolean;
  sections?: CollectionSections;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  seo?: Seo;
  slug?: InternationalizedArraySlug;
};

export type InternationalizedArraySlug = Array<{
  _key: string;
} & InternationalizedArraySlugValue>;

export type InternationalizedArrayText = Array<{
  _key: string;
} & InternationalizedArrayTextValue>;

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ProductSectionDesign | RangeSlider | ThemeContent | InternationalizedArrayString | Settings | AspectRatios | SanityImageCrop | SanityImageHotspot | Footer | Footers | Sections | Header | Padding | InternationalizedArrayLink | InternationalizedArrayAnnouncementBar | InternationalizedArrayHeaderNavigation | SocialLinksOnly | RichtextSection | RelatedProductsSection | ProductHeroSection | ImageBannerSection | FeaturedProductSection | FeaturedCollectionSection | CollectionProductGridSection | CollectionListSection | CollectionBannerSection | CarouselSection | ProductVariant | ShopifyProductVariant | ProxyString | Typography | CollectionRule | ShopifyCollection | Inventory | ShopifyProduct | PriceRange | PlaceholderString | Option | FontCategory | FontAsset | MegaMenu | NestedNavigation | Link | InternalLink | Button | HeaderNavigation | ExternalLink | Anchor | Seo | ProductSections | CollectionSections | SectionSettings | ColorScheme | ColorPicker | Richtext | ProductRichtext | ContentPosition | ContentAlignment | BannerRichtext | AnnouncementBar | InternationalizedArrayLinkValue | InternationalizedArrayBannerRichtextValue | InternationalizedArrayRichtextValue | InternationalizedArrayProductRichtextValue | InternationalizedArrayAnnouncementBarValue | InternationalizedArrayHeaderNavigationValue | InternationalizedArraySlugValue | InternationalizedArrayTextValue | InternationalizedArrayStringValue | InternationalizedArrayBannerRichtext | InternationalizedArrayRichtext | InternationalizedArrayProductRichtext | Home | Page | Slug | Product | ProductTemplate | Collection | CollectionTemplate | BlogPost | InternationalizedArraySlug | InternationalizedArrayText | Code | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
